FootBall.Web/Models/ClassificationViewModel.cs
using FootBall.Web.Data.Entities;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FootBall.Web.Models
{
    public class ClassificationViewModel : ClassificationEntity
    {
        public int TournamentId { get; set; }

        [Required(ErrorMessage = "The {0} field is required.")]
        [Display(Name = "Club")]
        [Range(1, int.MaxValue, ErrorMessage = "You must select a team.")]
        public int ClubId { get; set; }

        public IEnumerable<SelectListItem> Clubs { get; set; }
    }
}

FootBall.Web/Models/TournamentViewModel.cs
using FootBall.Web.Data.Entities;
using Microsoft.AspNetCore.Http;
using System.ComponentModel.DataAnnotations;

namespace FootBall.Web.Models
{
    public class TournamentViewModel : TournamentEntity
    {
        [Display(Name = "Logo")]
        public IFormFile LogoFile { get; set; }
    }
}

FootBall.Web/Controllers/SessionsController.cs
using FootBall.Web.Data;
using FootBall.Web.Data.Entities;
using FootBall.Web.Helpers;
using FootBall.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace FootBall.Web.Controllers
{
    public class SessionsController : Controller
    {
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IConverterHelper _converterHelper;

        public SessionsController(DataContext context, ICombosHelper combosHelper, IConverterHelper converterHelper)
        {
            _context = context;
            _combosHelper = combosHelper;
            _converterHelper = converterHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Sessions.ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TournamentEntity tournamentEntity = await _context.Tournaments.FindAsync(id);
            if (tournamentEntity == null)
            {
                return NotFound();
            }

            SessionViewModel model = new SessionViewModel
            {
                Tournament = tournamentEntity,
                TournamentId = tournamentEntity.Id,
                Types = _combosHelper.GetComboTypeSession()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SessionViewModel model)
        {
            if(ModelState.IsValid)
            {
                SessionEntity sessionEntity = await _converterHelper.ToSessionEntityAsync(model, true);
                _context.Add(sessionEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(Index)}/{model.TournamentId}");
            }

            model.Tournament = await _context.Tournaments.FindAsync(model.TournamentId);
            model.Types = _combosHelper.GetComboTypeSession();
            return View(model);
        }
    }
}

FootBall.Web/Controllers/TournamentsController.cs
using FootBall.Web.Data;
using FootBall.Web.Data.Entities;
using FootBall.Web.Helpers;
using FootBall.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace FootBall.Web.Controllers
{
    public class TournamentsController : Controller
    {
        private readonly DataContext _context;
        private readonly IConverterHelper _converterHelper;
        private readonly IImageHelper _imageHelper;
        private readonly ICombosHelper _combosHelper;

        public TournamentsController(DataContext context, IConverterHelper converterHelper, IImageHelper imageHelper, ICombosHelper combosHelper)
        {
            _context = context;
            _converterHelper = converterHelper;
            _imageHelper = imageHelper;
            _combosHelper = combosHelper;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context
                .Tournaments
                .Include(t => t.Sessions)
                .OrderBy(t => t.StartDate)
                .ToListAsync());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TournamentViewModel model)
        {
            if (ModelState.IsValid)
            {
                string path = string.Empty;
                if (model.LogoFile != null)
                {
                    path = await _imageHelper.UploadImageAsyc(model.LogoFile, "Tournaments");
                }

                TournamentEntity tournament = _converterHelper.ToTournamentEntity(model, path, true);
                _context.Add(tournament);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TournamentEntity tournamentEntity = await _context.Tournaments.FindAsync(id);
            if (tournamentEntity == null)
            {
                return NotFound();
            }

            TournamentViewModel model = _converterHelper.ToTournamentViewModel(tournamentEntity);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TournamentViewModel model)
        {
            if (ModelState.IsValid)
            {
                string path = model.LogoPath;
                if (model.LogoFile != null)
                {
                    path = await _imageHelper.UploadImageAsyc(model.LogoFile, "Tournaments");
                }

                TournamentEntity tournamentEntity = _converterHelper.ToTournamentEntity(model, path, false);
                _context.Update(tournamentEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournamentEntity = await _context.Tournaments.FirstOrDefaultAsync(t => t.Id == id);
            if (tournamentEntity == null)
            {
                return NotFound();
            }

            _context.Tournaments.Remove(tournamentEntity);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournamentEntity = await _context.Tournaments
                .Include(t => t.Classifications)
                .ThenInclude(c => c.Club)
                .FirstOrDefaultAsync(t => t.Id == id);

            if (tournamentEntity == null)
            {
                return NotFound();
            }

            return View(tournamentEntity);
        }

        public async Task<IActionResult> AddClubClassification(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TournamentEntity tournamentEntity = await _context.Tournaments.FindAsync(id);
            if(tournamentEntity == null)
            {
                return NotFound();
            }

            ClassificationViewModel model = new ClassificationViewModel
            {
                Tournament = tournamentEntity,
                TournamentId = tournamentEntity.Id,
                Clubs = _combosHelper.GetComboClubs()
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddClubClassification(ClassificationViewModel model)
        {
            if(ModelState.IsValid)
            {
                ClassificationEntity classificationEntity = await _converterHelper.ToClassificationEntityAsync(model, true);
                _context.Add(classificationEntity);
                await _context.SaveChangesAsync();
                return RedirectToAction($"{nameof(Details)}/{model.TournamentId}");
            }

            model.Tournament = await _context.Tournaments.FindAsync(model.TournamentId);
            model.Clubs = _combosHelper.GetComboClubs();
            return View(model);
        }
    }
}

FootBall.Web/Views/Tournaments/AddClubClassification.cshtml
@model FootBall.Web.Models.ClassificationViewModel

@{
    ViewData["Title"] = "Add Club";
}

<h2>Add</h2>

<h4>Team to tournament: @Model.Tournament.Name</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddClubClassification" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TournamentId" />

            <partial name="_Classification" />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Details" asp-route-id="@Model.TournamentId" class="btn btn-success">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootBall.Web/Views/Tournaments/Create.cshtml
@model FootBall.Web.Models.TournamentViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Tournament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <partial name="_Tournament" />

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-success">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootBall.Web/Views/Tournaments/Details.cshtml
@model FootBall.Web.Data.Entities.TournamentEntity

@{
    ViewData["Title"] = "Clasification";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />

<h2>Clasification</h2>

<div>
    <h4>Tournament</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.StartDateLocal)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.StartDateLocal)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.EndDateLocal)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.EndDateLocal)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.IsActive)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.IsActive)
                </dd>
            </dl>
        </div>
        <div class="col-md-4">
            @if (!string.IsNullOrEmpty(Model.LogoPath))
            {
                <img src="@Url.Content(Model.LogoPath)" alt="Image" style="width:150px;height:150px;max-width: 100%; height: auto;" />
            }
        </div>
    </div>
</div>
<div>
    <a asp-action="AddClubClassification" asp-route-id="@Model.Id" class="btn btn-primary">Add Club</a>
    <a asp-controller="Sessions" asp-action="Index" class="btn btn-info">Sessions</a>
    <a asp-action="Index" class="btn btn-success">Back to List</a>
</div>
<br />
@if (Model.Classifications.Count != 0)
{
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Clubs</h3>
                </div>
                <div class="panel-body">
                    <table class="table table-hover table-responsive table-striped" id="MyTable">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().Club.LogoPath)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().Club.Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GamesPlayed)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GamesWon)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GamesTied)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GamesLost)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().Points)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GoalsFor)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GoalsAgainst)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Classifications.FirstOrDefault().GoalsDifference)
                                </th>
                                <th width="100px"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Classifications.OrderByDescending(c => c.Points).ThenByDescending(c => c.GoalsDifference).ThenByDescending(c => c.GoalsFor))
                            {
                            <tr>
                                <td>
                                    @if (!string.IsNullOrEmpty(item.Club.LogoPath))
                                    {
                                        <img src="@Url.Content(item.Club.LogoPath)" alt="Image" style="width:50px;height:50px;max-width:100%;height:auto;" />
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Club.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GamesPlayed)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GamesWon)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GamesTied)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GamesLost)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Points)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GoalsFor)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GoalsAgainst)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.GoalsDifference)
                                </td>
                                <td>
                                    <!--a asp-action="EditClubClasification" asp-route="@item.Id" class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i></!-a>-->
                                    <button data-id="@item.Id" class="btn btn-danger deleteItem" data-toggle="modal" data-target="#deleteDialog"><i class="glyphicon glyphicon-trash"></i></button>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable();

            // Delete item
            var item_to_delete;

            $('.deleteItem').click((e) => {
                item_to_delete = e.currentTarget.dataset.id;
            });

            $("#btnYesDelete").click(function () {
                window.location.href = '/Tournaments/Delete/' + item_to_delete;
            });
        });
    </script>
}

FootBall.Web/Views/Tournaments/Edit.cshtml
@model FootBall.Web.Models.TournamentViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Tournament</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="LogoPath" />

            <partial name="_Tournament" />

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-success">Back to List</a>
            </div>
        </form>
    </div>
    <div class="col-md-4">
        @if (!string.IsNullOrEmpty(Model.LogoPath))
        {
            <img src="@Url.Content(Model.LogoPath)" alt="Image" style="width:200px;height:200px;max-width: 100%; height: auto;" />
        }
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootBall.Web/Views/Tournaments/Index.cshtml
@model IEnumerable<FootBall.Web.Data.Entities.TournamentEntity>

@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
<br />

<p>
    <a asp-action="Create" class="btn btn-primary"><i class="glyphicon glyphicon-plus"></i> Create New</a>
</p>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Tournaments</h3>
            </div>
            <div class="panel-body">
                <table class="table table-hover table-responsive table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.StartDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.EndDate)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LogoPath)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.IsActive)
                            </th>
                            <th>
                                # Sessions
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.StartDateLocal)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EndDateLocal)
                                </td>
                                <td>
                                    @if (!string.IsNullOrEmpty(item.LogoPath))
                                    {
                                        <img src="@Url.Content(item.LogoPath)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IsActive)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Sessions.Count)
                                </td>
                                <td>
                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info"><i class="glyphicon glyphicon-align-justify"></i></a>
                                    <button data-id="@item.Id" class="btn btn-danger deleteItem" data-toggle="modal" data-target="#deleteDialog"><i class="glyphicon glyphicon-trash"></i></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable();

            // Delete item
            var item_to_delete;

            $('.deleteItem').click((e) => {
                item_to_delete = e.currentTarget.dataset.id;
            });

            $("#btnYesDelete").click(function () {
                window.location.href = '/Tournaments/Delete/' + item_to_delete;
            });
        });
    </script>
}

FootBall.Web/Views/Tournaments/_Classification.cshtml
@model FootBall.Web.Models.ClassificationViewModel

<div class="form-group">
    <label asp-for="ClubId" class="control-label"></label>
    <select asp-for="ClubId" asp-items="Model.Clubs" class="form-control"></select>
    <span asp-validation-for="ClubId" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="GamesPlayed" class="control-label"></label>
    <input asp-for="GamesPlayed" class="form-control" />
    <span asp-validation-for="GamesPlayed" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="GamesWon" class="control-label"></label>
    <input asp-for="GamesWon" class="form-control" />
    <span asp-validation-for="GamesWon" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="GamesTied" class="control-label"></label>
    <input asp-for="GamesTied" class="form-control" />
    <span asp-validation-for="GamesTied" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="GamesLost" class="control-label"></label>
    <input asp-for="GamesLost" class="form-control" />
    <span asp-validation-for="GamesLost" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="GoalsFor" class="control-label"></label>
    <input asp-for="GoalsFor" class="form-control" />
    <span asp-validation-for="GoalsFor" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="GoalsAgainst" class="control-label"></label>
    <input asp-for="GoalsAgainst" class="form-control" />
    <span asp-validation-for="GoalsAgainst" class="text-danger"></span>
</div>

FootBall.Web/Views/Tournaments/_Tournament.cshtml
@model FootBall.Web.Models.TournamentViewModel

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="LogoFile" class="control-label"></label>
    <input asp-for="LogoFile" class="form-control" type="file" />
    <span asp-validation-for="LogoFile" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="StartDate" class="control-label"></label>
    <input asp-for="StartDate" class="form-control" />
    <span asp-validation-for="StartDate" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="EndDate" class="control-label"></label>
    <input asp-for="EndDate" class="form-control" />
    <span asp-validation-for="EndDate" class="text-danger"></span>
</div>

<div class="form-group">
    <div class="checkbox">
        <label>
            <input asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
        </label>
    </div>
</div>